version: "3.8"
services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:80"
# version: "3.8"

# services:
#     frontend:
#         build:
#             context: .
#             dockerfile: Dockerfile
#         volumes:
#             - react_build:/usr/share/nginx/html  # Делаем volume, чтобы Nginx видел файлы

#     # nginx:
#     #     image: nginx:1.23
#     #     container_name: nginx
#     #     ports:
#     #         - "80:80"  # Теперь Nginx в контейнере, поэтому маппим 80-й порт
#     #     volumes:
#     #         - react_build:/usr/share/nginx/html  # Используем собранный фронтенд
#     #         - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Подключаем конфиг Nginx
#     #     depends_on:
#     #         - frontend

# volumes:
#     react_build: