version: "3.8"
services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - /usr/share/nginx/html:/usr/share/nginx/html  # Прокидываем файлы наружу
        ports:
            - "3000:80"
