version: "3.8"

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:80"
    db:
        image: postgres:latest
        container_name: postgres_db
        environment:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
            POSTGRES_DB: mydatabase
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
    app:
        build:
            context: ./backend
            dockerfile: ./backend/Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - .:/app
        env_file:
            - backend/.env
        command: python -m ./backend/src

volumes:
    postgres_data:
