"""Add requires_participants flag

Revision ID: 150a75e885d6
Revises: 3cccbffcd35d
Create Date: 2024-12-10 20:48:30.348185

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '150a75e885d6'
down_revision: Union[str, None] = '3cccbffcd35d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events',
                  sa.Column('requires_participants', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))
    op.alter_column('events', 'requires_participants', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'requires_participants')
    # ### end Alembic commands ###
