"""Add participant role

Revision ID: 5c47071d8ba5
Revises: 150a75e885d6
Create Date: 2024-12-10 21:02:00.516809

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5c47071d8ba5'
down_revision: Union[str, None] = '150a75e885d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


participant_role_enum = sa.Enum('LISTENER', 'PARTICIPANT', name='participantrole')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    participant_role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'event_participants',
        sa.Column('role', participant_role_enum, nullable=False, server_default='LISTENER')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_participants', 'role')
    participant_role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
