"""add status for event particiaptions

Revision ID: be390edda070
Revises: fcbbe20acad4
Create Date: 2024-12-21 17:39:23.339269

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'be390edda070'
down_revision: Union[str, None] = 'fcbbe20acad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

participant_status_enum =  sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELED', name='participantstatus')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    participant_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('event_participants', sa.Column('status', participant_status_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_participants', 'status')
    # ### end Alembic commands ###
